// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.1.3

package v1

import (
	context "context"
	v1 "gitee.com/moyusir/util/api/util/v1"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type ConfigHTTPServer interface {
	UpdateDeviceConfig(context.Context, *v1.TestedDeviceConfig) (*ConfigServiceReply, error)
}

func RegisterConfigHTTPServer(s *http.Server, srv ConfigHTTPServer) {
	r := s.Route("/")
	r.POST("/configs", _Config_UpdateDeviceConfig0_HTTP_Handler(srv))
}

func _Config_UpdateDeviceConfig0_HTTP_Handler(srv ConfigHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in v1.TestedDeviceConfig
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.dataCollection.v1.Config/UpdateDeviceConfig")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateDeviceConfig(ctx, req.(*v1.TestedDeviceConfig))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ConfigServiceReply)
		return ctx.Result(200, reply)
	}
}

type ConfigHTTPClient interface {
	UpdateDeviceConfig(ctx context.Context, req *v1.TestedDeviceConfig, opts ...http.CallOption) (rsp *ConfigServiceReply, err error)
}

type ConfigHTTPClientImpl struct {
	cc *http.Client
}

func NewConfigHTTPClient(client *http.Client) ConfigHTTPClient {
	return &ConfigHTTPClientImpl{client}
}

func (c *ConfigHTTPClientImpl) UpdateDeviceConfig(ctx context.Context, in *v1.TestedDeviceConfig, opts ...http.CallOption) (*ConfigServiceReply, error) {
	var out ConfigServiceReply
	pattern := "/configs"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation("/api.dataCollection.v1.Config/UpdateDeviceConfig"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
