// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.17.3
// source: api/dataCollection/v1/warning_detect.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WarningDetectClient is the client API for WarningDetect service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WarningDetectClient interface {
	CreateStateInfoSaveStream0(ctx context.Context, opts ...grpc.CallOption) (WarningDetect_CreateStateInfoSaveStream0Client, error)
	CreateStateInfoSaveStream1(ctx context.Context, opts ...grpc.CallOption) (WarningDetect_CreateStateInfoSaveStream1Client, error)
}

type warningDetectClient struct {
	cc grpc.ClientConnInterface
}

func NewWarningDetectClient(cc grpc.ClientConnInterface) WarningDetectClient {
	return &warningDetectClient{cc}
}

func (c *warningDetectClient) CreateStateInfoSaveStream0(ctx context.Context, opts ...grpc.CallOption) (WarningDetect_CreateStateInfoSaveStream0Client, error) {
	stream, err := c.cc.NewStream(ctx, &WarningDetect_ServiceDesc.Streams[0], "/api.dataCollection.v1.WarningDetect/CreateStateInfoSaveStream0", opts...)
	if err != nil {
		return nil, err
	}
	x := &warningDetectCreateStateInfoSaveStream0Client{stream}
	return x, nil
}

type WarningDetect_CreateStateInfoSaveStream0Client interface {
	Send(*DeviceState0) error
	Recv() (*WarningDetectServiceReply, error)
	grpc.ClientStream
}

type warningDetectCreateStateInfoSaveStream0Client struct {
	grpc.ClientStream
}

func (x *warningDetectCreateStateInfoSaveStream0Client) Send(m *DeviceState0) error {
	return x.ClientStream.SendMsg(m)
}

func (x *warningDetectCreateStateInfoSaveStream0Client) Recv() (*WarningDetectServiceReply, error) {
	m := new(WarningDetectServiceReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *warningDetectClient) CreateStateInfoSaveStream1(ctx context.Context, opts ...grpc.CallOption) (WarningDetect_CreateStateInfoSaveStream1Client, error) {
	stream, err := c.cc.NewStream(ctx, &WarningDetect_ServiceDesc.Streams[1], "/api.dataCollection.v1.WarningDetect/CreateStateInfoSaveStream1", opts...)
	if err != nil {
		return nil, err
	}
	x := &warningDetectCreateStateInfoSaveStream1Client{stream}
	return x, nil
}

type WarningDetect_CreateStateInfoSaveStream1Client interface {
	Send(*DeviceState1) error
	Recv() (*WarningDetectServiceReply, error)
	grpc.ClientStream
}

type warningDetectCreateStateInfoSaveStream1Client struct {
	grpc.ClientStream
}

func (x *warningDetectCreateStateInfoSaveStream1Client) Send(m *DeviceState1) error {
	return x.ClientStream.SendMsg(m)
}

func (x *warningDetectCreateStateInfoSaveStream1Client) Recv() (*WarningDetectServiceReply, error) {
	m := new(WarningDetectServiceReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// WarningDetectServer is the server API for WarningDetect service.
// All implementations must embed UnimplementedWarningDetectServer
// for forward compatibility
type WarningDetectServer interface {
	CreateStateInfoSaveStream0(WarningDetect_CreateStateInfoSaveStream0Server) error
	CreateStateInfoSaveStream1(WarningDetect_CreateStateInfoSaveStream1Server) error
	mustEmbedUnimplementedWarningDetectServer()
}

// UnimplementedWarningDetectServer must be embedded to have forward compatible implementations.
type UnimplementedWarningDetectServer struct {
}

func (UnimplementedWarningDetectServer) CreateStateInfoSaveStream0(WarningDetect_CreateStateInfoSaveStream0Server) error {
	return status.Errorf(codes.Unimplemented, "method CreateStateInfoSaveStream0 not implemented")
}
func (UnimplementedWarningDetectServer) CreateStateInfoSaveStream1(WarningDetect_CreateStateInfoSaveStream1Server) error {
	return status.Errorf(codes.Unimplemented, "method CreateStateInfoSaveStream1 not implemented")
}
func (UnimplementedWarningDetectServer) mustEmbedUnimplementedWarningDetectServer() {}

// UnsafeWarningDetectServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WarningDetectServer will
// result in compilation errors.
type UnsafeWarningDetectServer interface {
	mustEmbedUnimplementedWarningDetectServer()
}

func RegisterWarningDetectServer(s grpc.ServiceRegistrar, srv WarningDetectServer) {
	s.RegisterService(&WarningDetect_ServiceDesc, srv)
}

func _WarningDetect_CreateStateInfoSaveStream0_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WarningDetectServer).CreateStateInfoSaveStream0(&warningDetectCreateStateInfoSaveStream0Server{stream})
}

type WarningDetect_CreateStateInfoSaveStream0Server interface {
	Send(*WarningDetectServiceReply) error
	Recv() (*DeviceState0, error)
	grpc.ServerStream
}

type warningDetectCreateStateInfoSaveStream0Server struct {
	grpc.ServerStream
}

func (x *warningDetectCreateStateInfoSaveStream0Server) Send(m *WarningDetectServiceReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *warningDetectCreateStateInfoSaveStream0Server) Recv() (*DeviceState0, error) {
	m := new(DeviceState0)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _WarningDetect_CreateStateInfoSaveStream1_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WarningDetectServer).CreateStateInfoSaveStream1(&warningDetectCreateStateInfoSaveStream1Server{stream})
}

type WarningDetect_CreateStateInfoSaveStream1Server interface {
	Send(*WarningDetectServiceReply) error
	Recv() (*DeviceState1, error)
	grpc.ServerStream
}

type warningDetectCreateStateInfoSaveStream1Server struct {
	grpc.ServerStream
}

func (x *warningDetectCreateStateInfoSaveStream1Server) Send(m *WarningDetectServiceReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *warningDetectCreateStateInfoSaveStream1Server) Recv() (*DeviceState1, error) {
	m := new(DeviceState1)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// WarningDetect_ServiceDesc is the grpc.ServiceDesc for WarningDetect service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WarningDetect_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.dataCollection.v1.WarningDetect",
	HandlerType: (*WarningDetectServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreateStateInfoSaveStream0",
			Handler:       _WarningDetect_CreateStateInfoSaveStream0_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "CreateStateInfoSaveStream1",
			Handler:       _WarningDetect_CreateStateInfoSaveStream1_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/dataCollection/v1/warning_detect.proto",
}
