// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gitee.com/moyusir/dataCollection/internal/biz"
	"gitee.com/moyusir/dataCollection/internal/conf"
	"gitee.com/moyusir/dataCollection/internal/data"
	"gitee.com/moyusir/dataCollection/internal/server"
	"gitee.com/moyusir/dataCollection/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	redisRepo := data.NewRedisRepo(dataData, logger)
	configUsecase := biz.NewConfigUsecase(redisRepo, logger)
	configService := service.NewConfigService(configUsecase, logger)
	warningDetectUsecase := biz.NewWarningDetectUsecase(redisRepo, logger)
	warningDetectService := service.NewWarningDetectService(warningDetectUsecase, logger)
	httpServer := server.NewHTTPServer(confServer, configService, warningDetectService, logger)
	grpcServer := server.NewGRPCServer(confServer, configService, warningDetectService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}

// init ConfigUsecase 测试用的辅助函数
func initConfigUsecase(confData *conf.Data, logger log.Logger) (*biz.ConfigUsecase, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	redisRepo := data.NewRedisRepo(dataData, logger)
	configUsecase := biz.NewConfigUsecase(redisRepo, logger)
	return configUsecase, func() {
		cleanup()
	}, nil
}

// init WarningDetectUsecase 测试用的辅助函数
func initWarningDetectUsecase(confData *conf.Data, logger log.Logger) (*biz.WarningDetectUsecase, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	redisRepo := data.NewRedisRepo(dataData, logger)
	warningDetectUsecase := biz.NewWarningDetectUsecase(redisRepo, logger)
	return warningDetectUsecase, func() {
		cleanup()
	}, nil
}
