// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gitee.com/moyusir/data-collection/internal/biz"
	"gitee.com/moyusir/data-collection/internal/conf"
	"gitee.com/moyusir/data-collection/internal/data"
	"gitee.com/moyusir/data-collection/internal/server"
	"gitee.com/moyusir/data-collection/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	unionRepo := data.NewRedisRepo(dataData, logger)
	configUsecase := biz.NewConfigUsecase(unionRepo, logger)
	routeManager, err := biz.NewRouteManager(confServer)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	configService, cleanup2, err := service.NewConfigService(configUsecase, routeManager, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	httpServer := server.NewHTTPServer(confServer, configService, logger)
	warningDetectUsecase := biz.NewWarningDetectUsecase(unionRepo, logger)
	warningDetectService := service.NewWarningDetectService(warningDetectUsecase, routeManager, logger)
	grpcServer := server.NewGRPCServer(confServer, configService, warningDetectService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
