server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  redis:
    host: redis.default.svc.cluster.local
    serverPort: 6379
    sentinelPort: 26379
    masterName: mymaster
    poolSize: 5
    minIdleConns: 2
