server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
    port: 80
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
  gateway:
    address: http://kong.test.svc.cluster.local:8001
    routeTimeout: 60s
data:
  redis:
    host: redis.default.svc.cluster.local
    serverPort: 6379
    sentinelPort: 26379
    masterName: mymaster
    poolSize: 5
    minIdleConns: 2
