server:
  http:
    addr: 0.0.0.0:8000
    timeout: 60s
    port: 8000
  grpc:
    addr: 0.0.0.0:9000
    timeout: 60s
data:
  redis:
    host: test-redis.test.svc.cluster.local
    serverPort: 6379
    sentinelPort: 26379
    masterName: mymaster
    poolSize: 5
    minIdleConns: 2
  influxdb:
    serverUrl: http://influxdb.test.svc.cluster.local:8086
    authToken: test
    org: test
