// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package test

import (
	"gitee.com/moyusir/data-collection/internal/biz"
	"gitee.com/moyusir/data-collection/internal/conf"
	"gitee.com/moyusir/data-collection/internal/data"
	"gitee.com/moyusir/data-collection/internal/server"
	"gitee.com/moyusir/data-collection/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	redisData, cleanup, err := data.NewRedisData(confData)
	if err != nil {
		return nil, nil, err
	}
	influxdbData, cleanup2, err := data.NewInfluxdbData(confData)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	unionRepo := data.NewRepo(redisData, influxdbData)
	configUsecase := biz.NewConfigUsecase(unionRepo, logger)
	routeManager, err := biz.NewRouteManager(confServer, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	configService, cleanup3, err := service.NewConfigService(configUsecase, routeManager, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	httpServer := server.NewHTTPServer(confServer, configService, logger)
	warningDetectUsecase := biz.NewWarningDetectUsecase(unionRepo, logger)
	warningDetectService := service.NewWarningDetectService(warningDetectUsecase, routeManager, logger)
	grpcServer := server.NewGRPCServer(confServer, configService, warningDetectService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// InitConfigUsecase 测试用的辅助函数
func InitConfigUsecase(confData *conf.Data, logger log.Logger) (*biz.ConfigUsecase, func(), error) {
	redisData, cleanup, err := data.NewRedisData(confData)
	if err != nil {
		return nil, nil, err
	}
	influxdbData, cleanup2, err := data.NewInfluxdbData(confData)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	unionRepo := data.NewRepo(redisData, influxdbData)
	configUsecase := biz.NewConfigUsecase(unionRepo, logger)
	return configUsecase, func() {
		cleanup2()
		cleanup()
	}, nil
}

// InitWarningDetectUsecase 测试用的辅助函数
func InitWarningDetectUsecase(confData *conf.Data, logger log.Logger) (*biz.WarningDetectUsecase, func(), error) {
	redisData, cleanup, err := data.NewRedisData(confData)
	if err != nil {
		return nil, nil, err
	}
	influxdbData, cleanup2, err := data.NewInfluxdbData(confData)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	unionRepo := data.NewRepo(redisData, influxdbData)
	warningDetectUsecase := biz.NewWarningDetectUsecase(unionRepo, logger)
	return warningDetectUsecase, func() {
		cleanup2()
		cleanup()
	}, nil
}
